// Söz bazası.
// Hər söz: [söz, ipucu, undercover sözü]
//  - ipucu: impostora göstərilən UZAQ assosiasiya. Sözün sinonimi, hissəsi
//    və ya eyni kateqoriyadan başqa söz OLMAMALIDIR — kateqoriya ilə birlikdə
//    bir neçə sözə uyğun gəlməlidir.
//  - undercover: "Undercover" rejimində impostora verilən oxşar, amma fərqli söz.

export const CATEGORIES = [
  {
    id: 'food',
    name: 'Yeməklər',
    emoji: '🍽️',
    words: [
      ['Plov', 'Toy', 'Dolma'],
      ['Dolma', 'Nənə', 'Plov'],
      ['Qutab', 'Yarımay', 'Kətə'],
      ['Dövğa', 'Yay', 'Ayran'],
      ['Kabab', 'İstirahət günü', 'Şaurma'],
      ['Pizza', 'Dairə', 'Lahmacun'],
      ['Burger', 'Sürət', 'Sendviç'],
      ['Şaurma', 'Gecə', 'Hot-doq'],
      ['Suşi', 'Çubuq', 'Pizza'],
      ['Şorba', 'Qış', 'Borş'],
      ['Piti', 'Doyurucu', 'Bozbaş'],
      ['Xəngəl', 'Sarımsaq', 'Düşbərə'],
      ['Düşbərə', 'Qaşıq', 'Xəngəl'],
      ['Paxlava', 'Qoz', 'Şəkərbura'],
      ['Şəkərbura', 'Naxış', 'Paxlava'],
      ['Omlet', 'Səhər', 'Bişmiş yumurta'],
      ['Salat', 'Pəhriz', 'Göyərti'],
      ['Makaron', 'Tələbə', 'Əriştə'],
      ['Kartof fri', 'Sous', 'Çips'],
      ['Dondurma', 'Uşaqlıq', 'Tort'],
      ['Tort', 'Sürpriz', 'Pirojna'],
      ['Çörək', 'Bərəkət', 'Lavaş'],
      ['Lavaş', 'Nazik', 'Yuxa'],
      ['Qovurma', 'Ehtiyat', 'Bozartma'],
      ['Bal', 'Qızıl', 'Mürəbbə'],
      ['Pendir', 'Ağ', 'Kəsmik'],
    ],
  },
  {
    id: 'fruit',
    name: 'Meyvə və tərəvəz',
    emoji: '🍎',
    words: [
      ['Alma', 'Bağ', 'Armud'],
      ['Armud', 'Çay', 'Heyva'],
      ['Banan', 'Sarı', 'Ananas'],
      ['Nar', 'Yaqut', 'Əncir'],
      ['Üzüm', 'Kiçik', 'Qarağat'],
      ['Qarpız', 'Böyük', 'Yemiş'],
      ['Yemiş', 'Ətir', 'Qarpız'],
      ['Limon', 'Vitamin', 'Portağal'],
      ['Portağal', 'Şirə', 'Mandarin'],
      ['Mandarin', 'Yeni il', 'Portağal'],
      ['Çiyələk', 'Qaymaq', 'Moruq'],
      ['Gilas', 'May', 'Albalı'],
      ['Ərik', 'Narıncı', 'Şaftalı'],
      ['Şaftalı', 'Yumşaq', 'Ərik'],
      ['Ananas', 'Tropik', 'Banan'],
      ['Kivi', 'Tük', 'Feyxoa'],
      ['Pomidor', 'Qırmızı', 'Bibər'],
      ['Xiyar', 'Yaşıl', 'Kabaçok'],
      ['Kartof', 'Torpaq', 'Şalğam'],
      ['Soğan', 'Qat', 'Sarımsaq'],
      ['Sarımsaq', 'Qoxu', 'Soğan'],
      ['Yerkökü', 'Dovşan', 'Çuğundur'],
      ['Badımcan', 'Bənövşəyi', 'Kabaçok'],
      ['Kələm', 'Turşu', 'Kahı'],
      ['Balqabaq', 'Payız', 'Yemiş'],
    ],
  },
  {
    id: 'animals',
    name: 'Heyvanlar',
    emoji: '🐾',
    words: [
      ['Pişik', 'Ev', 'İt'],
      ['İt', 'Sədaqət', 'Canavar'],
      ['Canavar', 'Ay', 'Tülkü'],
      ['Tülkü', 'Hiylə', 'Canavar'],
      ['Aslan', 'Kral', 'Pələng'],
      ['Pələng', 'Zolaq', 'Bəbir'],
      ['Fil', 'Nəhəng', 'Begemot'],
      ['Zürafə', 'Ləkə', 'Dəvə'],
      ['Dəvə', 'Səbir', 'At'],
      ['At', 'Yarış', 'Eşşək'],
      ['Eşşək', 'İnad', 'At'],
      ['İnək', 'Kənd', 'Camış'],
      ['Qoyun', 'Bulud', 'Keçi'],
      ['Keçi', 'Dağ', 'Qoyun'],
      ['Toyuq', 'Həyət', 'Ördək'],
      ['Ördək', 'Göl', 'Qaz'],
      ['Pinqvin', 'Soyuq', 'Suiti'],
      ['Delfin', 'Ağıl', 'Balina'],
      ['Köpəkbalığı', 'Qorxu', 'Delfin'],
      ['Meymun', 'Təqlid', 'Qorilla'],
      ['Ayı', 'Mağara', 'Panda'],
      ['Panda', 'Ağ-qara', 'Koala'],
      ['Dovşan', 'Qulaq', 'Dələ'],
      ['Dələ', 'Ağac', 'Dovşan'],
      ['İlan', 'Dəri', 'Kərtənkələ'],
      ['Tısbağa', 'Yavaş', 'İlbiz'],
      ['Qartal', 'Zirvə', 'Şahin'],
      ['Bayquş', 'Gecə', 'Qarğa'],
      ['Tutuquşu', 'Rəngarəng', 'Bülbül'],
      ['Kəpənək', 'Bahar', 'Cırcırama'],
      ['Arı', 'Zəhmət', 'Eşşəkarısı'],
    ],
  },
  {
    id: 'jobs',
    name: 'Peşələr',
    emoji: '👨‍⚕️',
    words: [
      ['Həkim', 'Ağ', 'Tibb bacısı'],
      ['Müəllim', 'Sentyabr', 'Tərbiyəçi'],
      ['Polis', 'Qayda', 'Əsgər'],
      ['Aşpaz', 'Dad', 'Qənnadçı'],
      ['Pilot', 'Eynək', 'Stüardessa'],
      ['Yanğınsöndürən', 'Nərdivan', 'Xilasedici'],
      ['Bərbər', 'Güzgü', 'Dərzi'],
      ['Dərzi', 'Ölçü', 'Bərbər'],
      ['Jurnalist', 'Sual', 'Bloger'],
      ['Proqramçı', 'Qəhvə', 'Dizayner'],
      ['Rəssam', 'İlham', 'Fotoqraf'],
      ['Fotoqraf', 'An', 'Operator'],
      ['Hakim', 'Tərəzi', 'Vəkil'],
      ['Vəkil', 'Kostyum', 'Prokuror'],
      ['Diş həkimi', 'Gülüş', 'Göz həkimi'],
      ['Kosmonavt', 'Ulduz', 'Pilot'],
      ['Müğənni', 'Səhnə', 'Aktyor'],
      ['Aktyor', 'Maska', 'Müğənni'],
      ['Sürücü', 'Tıxac', 'Kuryer'],
      ['Fermer', 'Çəkmə', 'Çoban'],
      ['Çoban', 'Dağ', 'Fermer'],
      ['Memar', 'Xətkeş', 'İnşaatçı'],
      ['İnşaatçı', 'Toz', 'Memar'],
      ['Satıcı', 'Endirim', 'Kassir'],
      ['Mühasib', 'Rəqəm', 'Bankir'],
      ['Psixoloq', 'Divan', 'Həkim'],
      ['Sehrbaz', 'Papaq', 'Kloun'],
      ['Kloun', 'Bayram', 'Sehrbaz'],
      ['Poçtalyon', 'Çanta', 'Kuryer'],
      ['Futbolçu', 'Azarkeş', 'Basketbolçu'],
    ],
  },
  {
    id: 'places_world',
    name: 'Ölkə və şəhərlər',
    emoji: '🌍',
    words: [
      ['Türkiyə', 'Körpü', 'Yunanıstan'],
      ['Rusiya', 'Qar', 'Kanada'],
      ['Gürcüstan', 'Qonşu', 'İran'],
      ['İran', 'Xalça', 'Türkiyə'],
      ['Yaponiya', 'Günəş', 'Çin'],
      ['Çin', 'İpək', 'Yaponiya'],
      ['Misir', 'Qum', 'Mərakeş'],
      ['İtaliya', 'Tarix', 'İspaniya'],
      ['İspaniya', 'Günorta yuxusu', 'Portuqaliya'],
      ['Fransa', 'Romantika', 'İtaliya'],
      ['Almaniya', 'Dəqiqlik', 'Avstriya'],
      ['İngiltərə', 'Yağış', 'Şotlandiya'],
      ['ABŞ', 'Azadlıq', 'Kanada'],
      ['Kanada', 'Meşə', 'ABŞ'],
      ['Braziliya', 'Karnaval', 'Argentina'],
      ['Hindistan', 'Ədviyyat', 'Pakistan'],
      ['Bakı', 'Külək', 'Gəncə'],
      ['Gəncə', 'Şair', 'Sumqayıt'],
      ['Şuşa', 'Musiqi', 'Şəki'],
      ['Şəki', 'Karvansaray', 'Qəbələ'],
      ['Qəbələ', 'Turist', 'Quba'],
      ['Quba', 'Sərin', 'Qusar'],
      ['Lənkəran', 'Çay', 'Astara'],
      ['Naxçıvan', 'Duz', 'Lənkəran'],
      ['İstanbul', 'Martı', 'İzmir'],
      ['Paris', 'Moda', 'London'],
      ['London', 'Saat', 'Paris'],
      ['Dubay', 'Rekord', 'Antalya'],
      ['Moskva', 'Metro', 'Sankt-Peterburq'],
      ['Nyu-York', 'Alma', 'Los-Anceles'],
      ['Roma', 'İmperiya', 'Afina'],
    ],
  },
  {
    id: 'sports',
    name: 'İdman',
    emoji: '⚽',
    words: [
      ['Futbol', 'Yaşıl', 'Reqbi'],
      ['Basketbol', 'Hündür', 'Voleybol'],
      ['Voleybol', 'Çimərlik', 'Basketbol'],
      ['Tennis', 'Sarı', 'Badminton'],
      ['Badminton', 'Həyət', 'Tennis'],
      ['Üzgüçülük', 'Xlor', 'Su polosu'],
      ['Boks', 'Zəng', 'Kikboksinq'],
      ['Güləş', 'Çiyin', 'Cüdo'],
      ['Cüdo', 'Kəmər', 'Karate'],
      ['Karate', 'Qışqırıq', 'Taekvondo'],
      ['Şahmat', 'Səssizlik', 'Dama'],
      ['Nərd', 'Çayxana', 'Domino'],
      ['Qaçış', 'Nəfəs', 'Marafon'],
      ['Qolf', 'Milyonçu', 'Bilyard'],
      ['Bilyard', 'Fizika', 'Bouling'],
      ['Bouling', 'Ayaqqabı', 'Bilyard'],
      ['Xokkey', 'Soyuq', 'Fiqurlu konkisürmə'],
      ['Fiqurlu konkisürmə', 'Fırlanma', 'Xokkey'],
      ['Xizək', 'Yamac', 'Snoubord'],
      ['Gimnastika', 'Balans', 'Akrobatika'],
      ['Atıcılıq', 'Nişan', 'Oxatma'],
      ['Oxatma', 'Meşə', 'Atıcılıq'],
      ['Sörfinq', 'Havay', 'Skeytbord'],
      ['Dağçılıq', 'İp', 'Turizm'],
      ['Formula 1', 'Şampan', 'Ralli'],
      ['Sumo', 'Çəki', 'Güləş'],
    ],
  },
  {
    id: 'home',
    name: 'Ev əşyaları',
    emoji: '🏠',
    words: [
      ['Divan', 'İstirahət', 'Kreslo'],
      ['Soyuducu', 'Gecə yarısı', 'Dondurucu'],
      ['Paltaryuyan', 'Corab', 'Qabyuyan'],
      ['Ütü', 'Buxar', 'Fen'],
      ['Fen', 'İsti', 'Ütü'],
      ['Tozsoran', 'Səs-küy', 'Süpürgə'],
      ['Süpürgə', 'Həyət', 'Tozsoran'],
      ['Güzgü', 'Nağıl', 'Pəncərə'],
      ['Pəncərə', 'Mənzərə', 'Qapı'],
      ['Qapı', 'Döymək', 'Pəncərə'],
      ['Çarpayı', 'Həftəsonu', 'Divan'],
      ['Yastıq', 'Döyüş', 'Yorğan'],
      ['Lampa', 'Fikir', 'Şam'],
      ['Şam', 'İşıq sönməsi', 'Lampa'],
      ['Televizor', 'Xəbərlər', 'Proyektor'],
      ['Saat', 'Gecikmə', 'Təqvim'],
      ['Qazan', 'Ocaq', 'Tava'],
      ['Çaydan', 'Fit', 'Samovar'],
      ['Bıçaq', 'Diqqət', 'Qayçı'],
      ['Qayçı', 'Kağız', 'Bıçaq'],
      ['Çətir', 'Unutmaq', 'Plaş'],
      ['Diş fırçası', 'Nanə', 'Daraq'],
      ['Daraq', 'Səhər', 'Diş fırçası'],
      ['Sabun', 'Qoxu', 'Şampun'],
      ['Dəsmal', 'Hamam', 'Xalat'],
      ['Açar', 'Sirr', 'Kilid'],
      ['Kondisioner', 'Yay', 'Ventilyator'],
    ],
  },
  {
    id: 'transport',
    name: 'Nəqliyyat',
    emoji: '🚗',
    words: [
      ['Avtomobil', 'Qaraj', 'Taksi'],
      ['Taksi', 'Gecə', 'Avtobus'],
      ['Avtobus', 'Sıxlıq', 'Metro'],
      ['Metro', 'Qaranlıq', 'Tramvay'],
      ['Tramvay', 'Zınqırov', 'Qatar'],
      ['Qatar', 'Səyahət', 'Tramvay'],
      ['Təyyarə', 'Bulud', 'Helikopter'],
      ['Helikopter', 'Xilasetmə', 'Təyyarə'],
      ['Gəmi', 'Dalğa', 'Qayıq'],
      ['Qayıq', 'Balıqçı', 'Yaxta'],
      ['Velosiped', 'Dizlər', 'Motosiklet'],
      ['Motosiklet', 'Dəri gödəkcə', 'Skuter'],
      ['Samokat', 'Səki', 'Velosiped'],
      ['Raket', 'Alov', 'Peyk'],
      ['Yük maşını', 'Ağır', 'Traktor'],
      ['Traktor', 'Palçıq', 'Yük maşını'],
      ['Təcili yardım', 'Ümid', 'Yanğın maşını'],
      ['Yanğın maşını', 'Qırmızı', 'Təcili yardım'],
      ['Hava şarı', 'Rəngarəng', 'Paraşüt'],
      ['Paraşüt', 'Cəsarət', 'Hava şarı'],
      ['Kanat yolu', 'Yüksəklik', 'Lift'],
      ['Lift', 'Düymə', 'Eskalator'],
      ['Kirşə', 'Qar', 'Xizək'],
      ['Sualtı qayıq', 'Sarı', 'Gəmi'],
      ['Limuzin', 'Toy', 'Avtomobil'],
    ],
  },
  {
    id: 'places',
    name: 'Məkanlar',
    emoji: '📍',
    words: [
      ['Məktəb', 'Zəng', 'Universitet'],
      ['Universitet', 'Kitab', 'Məktəb'],
      ['Xəstəxana', 'Növbə', 'Aptek'],
      ['Aptek', 'Ağrı', 'Xəstəxana'],
      ['Hava limanı', 'Gözləmə', 'Vağzal'],
      ['Vağzal', 'Vida', 'Hava limanı'],
      ['Çimərlik', 'Qum', 'Hovuz'],
      ['Hovuz', 'Mavi', 'Akvapark'],
      ['Kinoteatr', 'Bilet', 'Teatr'],
      ['Teatr', 'Pərdə', 'Kinoteatr'],
      ['Muzey', 'Keçmiş', 'Kitabxana'],
      ['Kitabxana', 'Sükut', 'Kitab mağazası'],
      ['Restoran', 'Bahşiş', 'Kafe'],
      ['Supermarket', 'Siyahı', 'Bazar'],
      ['Bazar', 'Təzə', 'Supermarket'],
      ['Park', 'Gəzinti', 'Bağ'],
      ['Zoopark', 'Qəfəs', 'Sirk'],
      ['Sirk', 'Çadır', 'Zoopark'],
      ['İdman zalı', 'Tər', 'Stadion'],
      ['Stadion', 'Qışqırıq', 'İdman zalı'],
      ['Bank', 'Faiz', 'Poçt'],
      ['Poçt', 'Marka', 'Bank'],
      ['Ofis', 'Bazar ertəsi', 'Fabrik'],
      ['Otel', 'Səhər yeməyi', 'Hostel'],
      ['Toy şadlığı', 'Rəqs', 'Restoran'],
      ['Ada', 'Tənhalıq', 'Çimərlik'],
      ['Mağara', 'Əks-səda', 'Tunel'],
      ['Həbsxana', 'Qaçış', 'Polis bölməsi'],
      ['Qəsr', 'Kral', 'Saray'],
    ],
  },
  {
    id: 'azerbaijan',
    name: 'Azərbaycan',
    emoji: '🇦🇿',
    words: [
      ['Qız Qalası', 'Əfsanə', 'Şirvanşahlar sarayı'],
      ['Alov qüllələri', 'Üç', 'Qız Qalası'],
      ['Bulvar', 'Axşam', 'Fəvvarələr meydanı'],
      ['Novruz', 'Bayram', 'Yeni il'],
      ['Xarıbülbül', 'Rəmz', 'Lalə'],
      ['Tar', 'UNESCO', 'Kamança'],
      ['Kamança', 'Yay', 'Tar'],
      ['Muğam', 'Ruh', 'Meyxana'],
      ['Meyxana', 'Bədahətən', 'Muğam'],
      ['Xalça', 'Uçan', 'Kəlağayı'],
      ['Kəlağayı', 'Bəzək', 'Xalça'],
      ['Qobustan', 'Daş', 'Palçıq vulkanları'],
      ['Yanardağ', 'Əbədi', 'Atəşgah'],
      ['Atəşgah', 'Qədim', 'Yanardağ'],
      ['Palçıq vulkanları', 'Boz', 'Qobustan'],
      ['Şahdağ', 'Qış', 'Tufandağ'],
      ['Göygöl', 'Zəlzələ', 'Maralgöl'],
      ['Xan sarayı', 'Rəsm', 'Şirvanşahlar sarayı'],
      ['İçərişəhər', 'Divar', 'Qız Qalası'],
      ['Səməni', 'Yaşıl', 'Buğda'],
      ['Tonqal', 'Atlamaq', 'Fişəng'],
      ['Kosa və Keçəl', 'Tamaşa', 'Şaxta baba'],
      ['Dədə Qorqud', 'Ağsaqqal', 'Koroğlu'],
      ['Koroğlu', 'Opera', 'Dədə Qorqud'],
      ['Molla Nəsrəddin', 'Gülüş', 'Bəhlul Danəndə'],
      ['Çay', 'Mürəbbə', 'Qəhvə'],
      ['Papaq', 'Qoyun', 'Çuxa'],
      ['Çuxa', 'Qafqaz', 'Papaq'],
    ],
  },
  {
    id: 'clothes',
    name: 'Geyim və aksesuar',
    emoji: '👕',
    words: [
      ['Köynək', 'Düymə', 'Futbolka'],
      ['Futbolka', 'Yay', 'Köynək'],
      ['Cins şalvar', 'Mavi', 'Şort'],
      ['Şort', 'Çimərlik', 'Cins şalvar'],
      ['Don', 'Bal', 'Yubka'],
      ['Yubka', 'Külək', 'Don'],
      ['Kostyum', 'Müsahibə', 'Pencək'],
      ['Qalstuk', 'Ofis', 'Şərf'],
      ['Şərf', 'Qış', 'Qalstuk'],
      ['Kepka', 'Günəş', 'Şlyapa'],
      ['Əlcək', 'Soyuq', 'Corab'],
      ['Corab', 'İtmək', 'Əlcək'],
      ['Ayaqqabı', 'Bağ', 'Çəkmə'],
      ['Çəkmə', 'Payız', 'Krossovka'],
      ['Krossovka', 'Brend', 'Ayaqqabı'],
      ['Terlik', 'Ana', 'Sandal'],
      ['Pijama', 'Gecə', 'Xalat'],
      ['Gödəkcə', 'Fermuar', 'Palto'],
      ['Palto', 'Asılqan', 'Gödəkcə'],
      ['Sviter', 'Nənə', 'Hudi'],
      ['Eynək', 'Kitab', 'Linza'],
      ['Qol saatı', 'Hədiyyə', 'Bilərzik'],
      ['Üzük', 'Barmaq', 'Sırğa'],
      ['Sırğa', 'Parıltı', 'Boyunbağı'],
      ['Boyunbağı', 'Mirvari', 'Üzük'],
      ['Çanta', 'Qarışıqlıq', 'Bel çantası'],
      ['Kəmər', 'Deşik', 'Qalstuk'],
    ],
  },
  {
    id: 'music',
    name: 'Musiqi',
    emoji: '🎵',
    words: [
      ['Gitara', 'Tonqal', 'Ukulele'],
      ['Piano', 'Ağ-qara', 'Sintezator'],
      ['Skripka', 'Çənə', 'Violonçel'],
      ['Baraban', 'Ürək', 'Nağara'],
      ['Nağara', 'Toy', 'Baraban'],
      ['Truba', 'Fil', 'Saksafon'],
      ['Saksafon', 'Gecə', 'Truba'],
      ['Fleyta', 'Quş', 'Balaban'],
      ['Balaban', 'Kədər', 'Zurna'],
      ['Zurna', 'Bayram', 'Balaban'],
      ['Mikrofon', 'Həyəcan', 'Qulaqlıq'],
      ['Qulaqlıq', 'Metro', 'Mikrofon'],
      ['Karaoke', 'Ekran', 'Konsert'],
      ['Konsert', 'Bilet', 'Festival'],
      ['Rep', 'Sürət', 'Meyxana'],
      ['Rok', 'Saç', 'Metal'],
      ['Caz', 'Duman', 'Blüz'],
      ['Opera', 'Şüşə', 'Balet'],
      ['Balet', 'Barmaq ucu', 'Opera'],
      ['Orkestr', 'Çubuq', 'Xor'],
      ['Xor', 'Birlik', 'Orkestr'],
      ['Himn', 'Ayağa qalxmaq', 'Marş'],
      ['Not', 'Yeddi', 'Akkord'],
      ['DJ', 'Pult', 'Müğənni'],
    ],
  },
  {
    id: 'tech',
    name: 'Texnologiya',
    emoji: '📱',
    words: [
      ['Telefon', 'Asılılıq', 'Planşet'],
      ['Planşet', 'Uşaq', 'Noutbuk'],
      ['Noutbuk', 'Kafe', 'Kompüter'],
      ['Smart saat', 'Addım', 'Fitnes qolbağı'],
      ['Robot', 'Gələcək', 'Süni intellekt'],
      ['Süni intellekt', 'Beyin', 'Robot'],
      ['Dron', 'Vızıltı', 'Helikopter'],
      ['Wi-Fi', 'Şifrə', 'Bluetooth'],
      ['İnternet', 'Hörümçək', 'Wi-Fi'],
      ['Selfi', 'Bucaq', 'Video'],
      ['Emoji', 'Hiss', 'Stiker'],
      ['Oyun konsolu', 'Rəqib', 'VR eynək'],
      ['VR eynək', 'Başqa dünya', 'Oyun konsolu'],
      ['Powerbank', 'Xilaskar', 'Şarj cihazı'],
      ['Şarj cihazı', 'Gecə', 'Powerbank'],
      ['Printer', 'Əsəb', 'Skaner'],
      ['Kamera', 'Xatirə', 'Telefon'],
      ['Klaviatura', 'Piano', 'Kompüter siçanı'],
      ['Kompüter siçanı', 'Pendir', 'Klaviatura'],
      ['Parol', 'Unutmaq', 'PIN kod'],
      ['Sosial şəbəkə', 'Vaxt itkisi', 'Messencer'],
      ['Naviqator', 'Sağa dönün', 'Xəritə'],
      ['QR kod', 'Kvadrat', 'Ştrix kod'],
    ],
  },
  {
    id: 'nature',
    name: 'Təbiət və hava',
    emoji: '🌳',
    words: [
      ['Göy qurşağı', 'Xəzinə', 'Qütb parıltısı'],
      ['Şimşək', 'Elektrik', 'Göy gurultusu'],
      ['Vulkan', 'Partlayış', 'Zəlzələ'],
      ['Zəlzələ', 'Şkala', 'Vulkan'],
      ['Dəniz', 'Duz', 'Okean'],
      ['Okean', 'Dərinlik', 'Dəniz'],
      ['Şəlalə', 'Duş', 'Bulaq'],
      ['Dağ', 'Uca', 'Təpə'],
      ['Meşə', 'Azmaq', 'Cəngəllik'],
      ['Səhra', 'Miraj', 'Çöl'],
      ['Ay', 'Gecə', 'Günəş'],
      ['Günəş', 'Enerji', 'Ay'],
      ['Ulduz', 'Arzu', 'Planet'],
      ['Bulud', 'Pambıq', 'Duman'],
      ['Duman', 'Sirr', 'Bulud'],
      ['Qar', 'Sükut', 'Dolu'],
      ['Tufan', 'Qəzəb', 'Qasırğa'],
      ['Ağac', 'Kölgə', 'Kol'],
      ['Gül', 'Sevgi', 'Lalə'],
      ['Kaktus', 'Qucaqlamaq', 'Aloe'],
      ['Göl', 'Qu quşu', 'Gölməçə'],
      ['Payız', 'Məktəb', 'Bahar'],
      ['Qış', 'Yeni il', 'Payız'],
      ['Yay', 'Tətil', 'Bahar'],
      ['Bahar', 'Allergiya', 'Yay'],
    ],
  },
  {
    id: 'movies',
    name: 'Film və cizgi filmləri',
    emoji: '🎬',
    words: [
      ['Titanik', 'Qapı', 'Avatar'],
      ['Avatar', 'Mavi', 'Titanik'],
      ['Harri Potter', 'Eynək', 'Üzüklərin hökmdarı'],
      ['Üzüklərin hökmdarı', 'Səyahət', 'Harri Potter'],
      ['Şrek', 'Bataqlıq', 'Buz dövrü'],
      ['Buz dövrü', 'Qoz', 'Şrek'],
      ['Madaqaskar', 'Rəqs', 'Aslan kral'],
      ['Aslan kral', 'Qaya', 'Madaqaskar'],
      ['Tom və Cerri', 'Qovmaq', 'Mikki Maus'],
      ['Mikki Maus', 'Əlcək', 'Tom və Cerri'],
      ['Spayder-Men', 'Qonşu', 'Betmen'],
      ['Betmen', 'Gecə', 'Spayder-Men'],
      ['Dəmir adam', 'Milyarder', 'Kapitan Amerika'],
      ['Frozen', 'Bacı', 'Rapunzel'],
      ['Rapunzel', 'Tava', 'Frozen'],
      ['Nemo', 'Ata', 'Su pərisi'],
      ['Su pərisi', 'Səs', 'Nemo'],
      ['Matrix', 'Həb', 'Terminator'],
      ['Terminator', 'Qayıdış', 'Matrix'],
      ['Arşın mal alan', 'Toy', 'O olmasın, bu olsun'],
      ['O olmasın, bu olsun', 'Pul', 'Arşın mal alan'],
      ['Kinq Konq', 'Banan', 'Qodzilla'],
      ['Qodzilla', 'Yaponiya', 'Kinq Konq'],
      ['Pinokkio', 'Yalan', 'Çippolino'],
      ['Çippolino', 'Bağ', 'Pinokkio'],
      ['Maşa və Ayı', 'Meşə', 'Tom və Cerri'],
      ['Ninja tısbağalar', 'Kanalizasiya', 'Spayder-Men'],
      ['Ceyms Bond', 'Martini', 'Missiya: Mümkünsüz'],
    ],
  },
  {
    id: 'events',
    name: 'Bayram və tədbirlər',
    emoji: '🎉',
    words: [
      ['Toy', 'Qohumlar', 'Nişan'],
      ['Nişan', 'Şirni', 'Toy'],
      ['Ad günü', 'Şam', 'Yubiley'],
      ['Yeni il', 'Saat', 'Ad günü'],
      ['Məzuniyyət', 'Papaq', 'Son zəng'],
      ['Son zəng', 'Lent', 'Məzuniyyət'],
      ['Bilik günü', 'Gül', 'Son zəng'],
      ['Hellouin', 'Kostyum', 'Maskarad'],
      ['Maskarad', 'Sirr', 'Hellouin'],
      ['Piknik', 'Qarışqa', 'Kamp'],
      ['Kamp', 'Ulduzlar', 'Piknik'],
      ['Sevgililər günü', 'Qırmızı', '8 Mart'],
      ['8 Mart', 'Çiçək', 'Sevgililər günü'],
      ['Ziyafət', 'Masa', 'Qonaqlıq'],
      ['Fişəng şousu', 'İt', 'Tonqal'],
      ['Ekskursiya', 'Avtobus', 'Səyahət'],
      ['Səyahət', 'Pasport', 'Ekskursiya'],
      ['Olimpiada', 'Halqa', 'Çempionat'],
      ['Xınayaxdı', 'Qız evi', 'Nişan'],
      ['Sürpriz ziyafət', 'Gizlənmək', 'Ad günü'],
      ['Festival', 'İzdiham', 'Konsert'],
    ],
  },
];

export function getCategory(id) {
  return CATEGORIES.find((c) => c.id === id);
}

export const TOTAL_WORDS = CATEGORIES.reduce((n, c) => n + c.words.length, 0);
